server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${dbHost}:${dbPort}/wordle?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${dbUser}
    password: ${dbPassword}
  jpa:
    hibernate:
      ddl-auto: ${dbDdlAuto}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
